### ISSUE TITLE
Implement sourcemap support

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-prepare#3]
I think we should implement the sourcemap logic into vinyl-prepare so it can be configured per-file (like all the other options).  This would also allow dependent adapters/libraries to have sourcemap support out-of-the-box.

Depends on https://github.com/floridoo/gulp-sourcemaps/issues/208

@doowb @jonschlinkert what do you guys think about having this here?

**Comment by jonschlinkert** [comment]
Ironically I just mentioned something to @doowb about the sourcemap logic recently. 

Would it make sense to implement sourcemaps as another library that consumes/wraps this one? It would be great to keep vinyl-prepare as generalized as possible, but I don't have any strong views on this.  I think sourcemaps would be a nice feature either way.

**Comment by phated** [comment]
I think the `gulp-sourcemaps` logic needs to me made as a standalone library (and then wrapped in a stream to become gulp-sourcemaps); it could then be consumed in this library.  Consumers could disable it by forcing the `sourcemaps` option to false.

**Comment by doowb** [comment]
> made as a standalone library

I agree that it should be a standalone library that has 2 methods (`init/write` or `src/dest`) that take a vinyl `file` and an `options` object.

Then libraries can use it in their streams like:

```js
through.obj(function(file, enc, next) {
  var opts = extend({}, options, file.options);
  sourcemaps.src(file, opts);
  next(null, file);
});
```

This gives more control over sourcemap options to users, (e.g. they can have another plugin that modifies individual file options before getting to this plugin). It also lets `vinyl-fs#src` take a function as the `sourcemaps` option to allow users to customize file options similar to the other options functions.

> Would it make sense to implement sourcemaps as another library that consumes/wraps this one? 

I like this since it reduces logic in `vinyl-prepare` but it also adds another layer to the sourcemaps library. Maybe if `gulp-sourcemaps` was updated to use the "new" `vinyl-sourcemaps` described above, then `vinyl-fs` would be able to do something like:

```js
vfs.src(options) // read
  .pipe(prepare.src(options)) // transform to vinyl
  .pipe(sourcemaps.src(options)); // init sourcemaps

//and
sourcemaps.dest(options) // create/write source maps
  .pipe(prepare.dest(options))  // transform destination paths
  .pipe(vfs.dest(options)); // write destination files
```

I've only quickly looked through the sourcemaps code, so I might be missing something, but I think that decoupling these libraries here and combining them in higher level adapters (like vinyl-fs) will be better.

**Comment by phated** [comment]
It looks like @robinvenneman is doing awesome work on this at https://github.com/robinvenneman/vinyl-sourcemaps - Keeping an eye on the progress.

**Comment by robinvenneman** [comment]
https://github.com/robinvenneman/vinyl-sourcemap should be ready to use, it has `add` & `write` methods. Perhaps I can look into this as well.

**Comment by phated** [comment]
@robinvenneman awesome!  I'll take a look soon

**Comment by phated** [comment]
I just published vinyl-sourcemap v0.1.0 at https://www.npmjs.com/package/vinyl-sourcemap

This is a very rough version based on gulp-sourcemaps.  It's a starting place for integration in this library but we'll be opening issues and changing things on it as we encounter them here.  I don't like the current API so I expect a lot to change.

**Comment by phated** [comment]
The filesystem stuff in vinyl-sourcemap feels weird when applied to vinyl-prepare.  I might not put it into this project and instead depend on it directly in vinyl-fs (also doesn't feel great).

**Comment by phated** [comment]
I don't like sourcemaps being jammed inside this library.  I'm going to embed vinyl-sourcemap into vinyl-fs directly.
